version: "3.7"
services:
  app:
    image: harobed/poc-generate-pdf-with-html-template-and-jsonschema:latest
    cap_add:
      - SYS_ADMIN
    ports:
      - 5000:5000
    environment:
      - SITE_URL=http://localhost:5000
    volumes:
      - ../pdf-templates/:/templates/